services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      network: host
      args:
        UID: 1000
        GID: 1000
    container_name: ${CONTAINER_NAME}
    ports:
      - "${CONTAINER_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    dns:
    - 8.8.8.8
    - 1.1.1.1

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "${DB_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PGADMIN_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    depends_on:
      - db

  db:
    container_name: ${CONTAINER_NAME=}
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: